Vagrant.configure("2") do |config|

  # Vm
  config.vm.box = "ubuntu/trusty64"

  # Provision
  config.vm.provision :shell, path: "bootstrap.sh"

  # Network
  config.vm.network "forwarded_port", guest: 443, host: 8080, id: "https"
  config.vm.network "forwarded_port", guest: 80, host: 8081, id: "nginx"
  config.vm.network "forwarded_port", guest: 22, host: 8082, id: "ssh"
end
