Vagrant.configure("2") do |config|

  # Vm
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder ".", "/vagrant"
  
  # Provision
  config.vm.provision :shell, path: "bootstrap.sh"

  # Network
  config.vm.network "forwarded_port", guest: 80, host: 8080, id: "nginx"

config.vm.provider :virtualbox do |vb|

  vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "2"]
end

end


